[package]
name = "ast-grep-language"
version = "0.1.14"
authors = ["Herrington Darkholme <2883231+HerringtonDarkholme@users.noreply.github.com>"]
edition = "2021"
description = "Search and Rewrite code at large scale using precise AST pattern"
keywords = ["ast", "pattern", "codemod", "search", "rewrite"]
license = "MIT"
repository = "https://github.com/ast-grep/ast-grep"
rust-version = "1.63"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ast-grep-core = { version="0.1.14", path = "../core" }
ignore = "0.4.18"
serde = { version = "1.0", features = ["derive"] }

tree-sitter-c = "0.20.2"
tree-sitter-go = "0.19.1"
tree-sitter-html = "0.19.0"
tree-sitter-java = "0.20.0"
tree-sitter-javascript = "0.20.0"
tree-sitter-kotlin = "0.2.11"
tree-sitter-lua = "0.0.14"
tree-sitter-python = "0.20.2"
tree-sitter-rust = "0.20.3"
tree-sitter-swift = "0.3.4"
tree-sitter-typescript="0.20.1"
tree-sitter-c-sharp = { version = "0.20.0", package = "ast-grep-tree-sitter-c-sharp" }
