[package]
name = "ast-grep-core"
version = "0.1.14"
authors = ["Herrington Darkholme <2883231+HerringtonDarkholme@users.noreply.github.com>"]
edition = "2021"
description = "Search and Rewrite code at large scale using precise AST pattern"
keywords = ["ast", "pattern", "codemod", "search", "rewrite"]
license = "MIT"
repository = "https://github.com/ast-grep/ast-grep"
rust-version = "1.63"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = {version = "1.7.0", optional = true }
tree-sitter = { version = "0.9", package = "tree-sitter-facade-sg" }
bit-set = "0.5.3"

[features]
default = ["regex"]

[dev-dependencies]
tree-sitter-typescript="0.20.1"
